Deloitte_Dynamics/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main import views


urlpatterns = [
    url(r'^accounts/password_change', views.dynamics_password_change, name="password_change"),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls'))
]

main/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.load, name='load'),
    url(r'^load/', views.load, name='load'),
    url(r'^alt_keys', views.keyword_upload, name='upload'),
    url(r'^sap/', views.sap_integration, name='sap'),
    url(r'^contents/', views.contents, name='contents'),
    # url(r'^tables/', views.table_load, name='table_load'),
    url(r'^report/', views.stored_searches, name='reports'),
    url(r'^stored_search/', views.stored_searches, name='stored_search'),
    url(r'^results', views.results, name='results'),
    url(r'^check_file_selected', views.check_file_selected, name='check_file_selected'),
    url(r'^edit_cmp_description', views.edit_cmp_description, name='edit_cmp_description'),
    url(r'^change_country', views.change_country, name='change_country'),
    url(r'^edit_member_firm_country', views.edit_member_firm_country, name='edit_member_firm_country'),
]

main/forms.py
import os

from django import forms
from main import models
from Deloitte_Dynamics.settings import PATH_TO_PDF_FILES

# ----
# -----

class KeywordForm(forms.Form):
    """
    A form to search for keywords.

    Fields:
        keywords: a CharField that contains a list of keywords separated
        by a comma.
    """
    keywords = forms.CharField(label="", max_length=140)


class DescriptionSelectionForm(forms.Form):
    """
    This form is for selecting a search from the active search set, the
    searches are sorted into empty, filled, not found and skipped. On
    selection, this form submits.

    Fields:
        search: a ChoiceField displaying all the searches, sorted as
        above.
    """
    def __init__(self, empty, filled, initial, not_found, skipped):
        super(DescriptionSelectionForm, self).__init__(initial)
        self.empty = empty
        self.filled = filled
        self.not_found = not_found
        self.skipped = skipped
        sorted_search_lists = {
            'Incomplete': self.empty,
            'Skipped': self.skipped,
            'Not Found': self.not_found,
            'Complete': self.filled,
        }
        choices = []

        for key, search_list in sorted_search_lists.items():
            if sorted_search_lists[key]:
                sub_choices = [(search['description'],
                                search['description'])
                               for search in search_list]
                choices.append(
                    (key,
                     sub_choices)
                )

        search = forms.ChoiceField(choices=choices, )
        search.widget.attrs.update({'onchange': 'this.form.submit()'})
        search.widget.attrs.update({'style': "max-width:50%;"})
        self.fields['search'] = search


# This is the form for inputting the results that have been found
class ResultForm(forms.Form):
    """
    This form is for inputting results that have been found. It takes
    the result, unit and timestamp. The width of these inputs is hard
    coded to 70 pixels.

    Fields:
        result: a CharField for the value of the result
        unit: a CharField for the unit of the result
        result: a CharField for the timestamp of the result

    """
    input_widget = forms.TextInput(attrs={'style': 'width: 70px'})
    result = forms.CharField(max_length=140, label='Result',
                             widget=input_widget, required=False)
    unit = forms.CharField(max_length=140, label='Unit',
                            widget=input_widget, required=False)
    timestamp = forms.CharField(max_length=140, label='Timestamp',
                                widget=input_widget, required=False)
    notes = forms.CharField(max_length=140, label='Notes',
                            widget=input_widget, required=False)


# This is the form to add a new set of alternative keywords
class AlternativesForm(forms.Form):
    """
    This form is for inputting an alternative keyword.

    Fields:
        alternative_keyword: a CharField for the keyword being added
    """
    alternative_keyword = forms.CharField(label="",
                                          max_length=200)


class FileForm(forms.Form):
    def __init__(self, path, extension, prefix=None, check_box=False, country_form=False, **kwargs):
        """
        This form is for selecting files/folders. It has an optional
        checkbox and must be passed the desired file extension. It
        only displays paths with the given extension.

        Fields:
            file: a FilePathField for the file that is being selected
            check: a BooleanField for the (optional) check box.
            country:

        """
        super(FileForm, self).__init__(**kwargs)
        file = forms.FilePathField(label='',
                                   path=path,
                                   allow_files=True,
                                   recursive=True)

        # country_obj = [(cnt_mdl.country_name, cnt_mdl.country_name) for cnt_mdl in models.Country.objects.all()]
        # country_obj = [('All', 'All')] + country_obj
        # country = forms.ChoiceField(label='', choices=country_obj)
        choices = []
        # country_choices = ["UK", "Canada"]
        # country.widget.choices = country_choices
        sub_folders = {}
        for path, name in file.choices:
            if path.endswith(".{}".format(extension)):
                name = name.strip(r"\\")
                if "\\" in name:
                    stages = os.path.split(name)
                    folder = stages[0]
                    name = "\\".join(stages[1:])
                    if folder not in sub_folders:
                        sub_folders[folder] = []
                    sub_folders[folder].append((path, name))
                else:
                    choices.append((path, name))
        for i, folder in enumerate(sub_folders):
            choices.append((folder, sub_folders[folder]))
        file.widget.choices = choices

        # file.widget.attrs.update(
        #     {'data-live-search': 'true', 'class': "selectpicker"})
        # file.widget.attrs.update(
        #     {'class': 'selectpicker show-tick form-control', 'data-live-search': "true"})

        if prefix:
            self.fields['{}_file'.format(prefix)] = file
        elif country_form == False:
            self.fields['file'] = file
        if check_box:
            self.fields['check'] = forms.BooleanField(label=check_box,
                                                      required=False)
        if country_form == True:
            opration_country_object = models.Country.objects.all()
            # ------------------------------------------------- #
            country_obj = [('All', 'All')]
            for row in opration_country_object:
                country_obj.append((row.Alpha_3_code, str(row.Country + "-" + row.Alpha_3_code)))
            country = forms.ChoiceField(label='', choices=country_obj)

            self.fields['country'] = country

Deloitte_Dynamics/templates/shared/css_includes.html
{% load staticfiles %}
<link href="{% static "assets/plugins/select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/bootstrap.min.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/core.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/components.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/icons.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/pages.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/responsive.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/plugins/x-editable/css/bootstrap-editable.css" %}" rel="stylesheet" type="text/css" />
<link href="{% static "assets/css/custom.css" %}" rel="stylesheet" type="text/css" />

<link rel="stylesheet" href="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.css" />

Deloitte_Dynamics/templates/shared/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Deloitte Dynamics">
        <meta name="author" content="Deloitte-DA">

        <link rel="shortcut icon" href="{% static "assets/images/favicon.ico" %}">

        <title>{% block tab_title %}Deloitte Dynamics{% endblock tab_title %}</title>

        {% block css_includes %}
        {% include 'shared/css_includes.html' %}
        {% endblock css_includes %}

        {% block css_includes_additional %}
        {% endblock css_includes_additional %}
        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static "assets/js/modernizr.min.js" %}"></script>

        <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>-->

    </head>

    <body class="fixed-left">

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            {% include 'shared/topbar.html' %}
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->
            {% block side_bar %}
            {% include 'shared/sidebar.html' %}
            {% endblock %}
            <!-- Left Sidebar End -->

            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page" style="height: 100%">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <!-- Page-Title -->
                        <div class="row">
                            <div class="col-sm-12">
                            {% block breadcrumb %}
                            {% if user.is_authenticated %}
                                {% if file %}
                                    <h4 class="page-title">{{ file.name }}</h4>
                                {% else %}
                                    <h4 class="page-title">Select File</h4>
                                {% endif %}
                            {% else %}
                                <h4 class="page-title">Login</h4>
                                <br>
                            {% endif %}
                            {% endblock breadcrumb %}
                            </div>
                        </div>
                        <br>
                        <div class="row">
                            {% block file %}
                            {% endblock %}
                            {% block page_body %}
                            {% endblock page_body %}
                        </div>
                    </div> <!-- container -->

                </div> <!-- content -->

                <footer class="footer">
                    © Deloitte LLP 2018. All rights reserved.
                </footer>

            </div>
            <!-- ============================================================== -->
            <!-- End Right content here -->
            <!-- ============================================================== -->

        </div>
        <!-- END wrapper -->

        <script>
            var resizefunc = [];
        </script>
        <!-- jQuery  -->
        {% block js_includes %}
        {% include 'shared/js_includes.html' %}
        <!--<script src="{% static "assets/js/jquery.min.js" %}"></script>-->
        <!--<script src="{% static "assets/js/bootstrap.min.js" %}"></script>-->
        <!--<script src="{% static "assets/js/detect.js" %}"></script>-->
        <!--<script src="{% static "assets/js/fastclick.js" %}"></script>-->
        <!--<script src="{% static "assets/js/jquery.slimscroll.js" %}"></script>-->
        <!--<script src="{% static "assets/js/jquery.blockUI.js" %}"></script>-->
        <!--<script src="{% static "assets/js/waves.js" %}"></script>-->
        <!--<script src="{% static "assets/js/wow.min.js" %}"></script>-->
        <!--<script src="{% static "assets/js/jquery.nicescroll.js" %}"></script>-->
        <!--<script src="{% static "assets/js/jquery.scrollTo.min.js" %}"></script>-->
        <!--<script src="{% static "assets/plugins/select2/js/select2.min.js" %}" type="text/javascript"></script>-->
        <!--<script src="{% static "assets/plugins/bootstrap-select/js/bootstrap-select.min.js" %}" type="text/javascript"></script>-->
        <!--<script src="{% static "assets/plugins/x-editable/js/bootstrap-editable.min.js" %}" type="text/javascript"></script>-->
        <!--<script src="{% static "assets/js/jquery.core.js" %}"></script>-->
        <!--<script src="{% static "assets/js/jquery.app.js" %}"></script>-->


        {% endblock js_includes %}
        {% block js_includes_additional %}
            <script type="text/javascript">
                function fetchTable() {
                    var tableID = $("#tableID").val();
                    window.location.replace("/view/"+tableID);
                }
                function fetchReviewTable() {
                    var tableID = $("#tableID").val();
                    window.location.replace("/review/"+tableID);
                }
            </script>
            <script type="text/javascript">
            $(document).ready(function(){
              // Initialize select2
              $("#id_file").select2();
              $("#id_country").select2();
              $("#id_search_file").select2();

              // For search added in hidden filed
              try{
                      // For search added in hidden filed
                      var e = document.getElementById("id_search");
                      var select_val = e.options[e.selectedIndex].value;  //selected_drp
                      console.log("select_val: ", select_val)
                      document.getElementById("selected_drp").value = select_val
                      $(".select2").select2();
                    }
              catch(err){
                console.log(err.message);
                    }
            });
              $(".select2").select2();

            </script>
            <script>
                 $("#id_file").change(function () {
                  var filename = $(this).val();
                  //alert(filename)
                  $.ajax({
                    url: '/check_file_selected',
                    data: {
                      'filename': filename
                    },
                    dataType: 'json',
                    success: function (data) {
                      if (data.is_selected) {
                        alert("This file is previously loaded with " + data.file_name);
                        console.log("This file is previously loaded with " + data.file_name);
                      }
                    }
                  });

                });
              </script>

            <script>
                 $("#id_country").change(function () {
                  var countryName = $(this).val();
                  // alert(countryName)
                  $.ajax({
                    url: '/change_country',
                    data: {
                      'countryName': countryName
                    },
                    dataType: 'json',
                    success: function (data) {
                      if (data.is_edited) {
                        // alert(data.file_form);
                        $("#id_file").html(data.file_form);

                      }
                    }
                  });

                });
              </script>

<script type="text/javascript">
var idleTime = 0;
$(document).ready(function () {
    //Increment the idle time counter every minute.
    var idleInterval = setInterval(timerIncrement, 60*1000); // 1 minute

    //Zero the idle timer on mouse movement.
    $(this).mousemove(function (e) {
        idleTime = 0;
        bootbox.hideAll();
    });
    $(this).keypress(function (e) {
        idleTime = 0;
        bootbox.hideAll();
    });
});

function timerIncrement() {
    idleTime = idleTime + 1;
    if (idleTime > 29) { // 2 minutes
        if(window.location.href.indexOf("accounts/login/") > -1)
                { //do nothing
                }
                else
                {
                   bootbox.dialog({ message: "You'll get logged out in <span id='SecondsRemaining'>60</span> seconds. Click on the page to continue"});
                   check();
                }
    }

    if (idleTime > 30) { // 30 minutes
        if(window.location.href.indexOf("accounts/login/") > -1)
                { //do nothing
                }
                else
                {

                 //window.location.href = "accounts/login/";
                 window.location = "/accounts/login/";

                }
    }
}

function timecounter(){
// Set the date we're counting down to
var countDownDate = new Date().getTime() + 60000;
// Update the count down every 1 second
var x = setInterval(function() {

  // Get todays date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);
  alert(seconds)
  // Output the result
  return seconds;
  }, 1000);
}

function check(){
    var remaining = 59; // Number of seconds
    var obj = document.getElementById("SecondsRemaining");
    var timeout = window.setInterval(function(){
        remaining--;
        if(remaining==0) {
            // Time is up, stop the timer and hide the bootbox
            window.clearInterval(timeout);
            bootbox.hideAll();
            return;
        }
        obj.innerHTML = remaining; // Update the value displayed
    }, 1000); // Decrease counter every second
}
</script>

        {% endblock js_includes_additional %}
    </body>
</html>

Deloitte_Dynamics/templates/shared/js_includes.html
{% load staticfiles %}

<script src="{% static "assets/js/jquery.min.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

<script src="{% static "assets/js/bootstrap.min.js" %}"></script>
<script src="{% static "assets/js/detect.js" %}"></script>
<script src="{% static "assets/js/fastclick.js" %}"></script>
<script src="{% static "assets/js/jquery.slimscroll.js" %}"></script>
<script src="{% static "assets/js/jquery.blockUI.js" %}"></script>
<script src="{% static "assets/js/waves.js" %}"></script>
<script src="{% static "assets/js/wow.min.js" %}"></script>
<script src="{% static "assets/js/jquery.nicescroll.js" %}"></script>
<script src="{% static "assets/js/jquery.scrollTo.min.js" %}"></script>
<script src="{% static "assets/plugins/select2/js/select2.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/plugins/bootstrap-select/js/bootstrap-select.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/plugins/x-editable/js/bootstrap-editable.min.js" %}" type="text/javascript"></script>
<script src="{% static "assets/js/jquery.core.js" %}"></script>
<script src="{% static "assets/js/jquery.app.js" %}"></script>

<script src="//cdn.jsdelivr.net/bootstrap.tagsinput/0.4.2/bootstrap-tagsinput.min.js"></script>

<!--<script src="{% static "assets/js/bootbox.min.js"%}"></script>-->
<!--<script src="{% static "assets/js/bootbox.all.min.js"%}"></script>-->
<!--<script src="{% static "assets/js/bootbox.js"%}"></script>-->
<!--<script src="{% static "assets/js/bootbox.locales.js"%}"></script>-->
<!--<script src="{% static "assets/js/bootbox.locales.min.js"%}"></script>-->

Deloitte_Dynamics/templates/shared/sidebar.html
{% load staticfiles %}
{% include 'shared/css_includes.html' %}
<!DOCTYPE html>
<html>
    <body>
    <!-- ========== Left Sidebar Start ========== -->

        <div class="left side-menu" style="width:150px">
            <div class="sidebar-inner slimscrollleft">
                <!--- Divider -->
                {% block leftmenu %}
                <div id="sidebar-menu">
                    <ul>
                        <li class="text-muted menu-title">Settings</li>
                        {% block alt_keywords %}
                        <li>
                            <a id="sidebar-alts" href="/alt_keys" class="waves-effect">
                                <i class="ti-upload"></i>
                                <span>Keywords</span>
                            </a>
                        </li>
                        {% endblock %}
                        {% block sap_link %}
                        <li>
                            <a id="sap-upload" href="/sap" class="waveseffect">
                                <i class="ti-reload"></i>
                                <span>Load SAP</span>
                            </a>
                        </li>
                        {% endblock %}
                        <li class="text-muted menu-title">Process</li>

                        {% block leftmenu_home %}
                        <li>
                            <a id="sidebar-load" href="/" class="waves-effect">
                                <i class="ti-home"></i>
                                <span>1) Load</span>
                            </a>
                        </li>
                        {% endblock leftmenu_home %}
                        {% block contents_link %}
                        <li>
                            <a id="sidebar-scan" href="/contents" class="waves-effect">
                                <i class="ti-book"></i>
                                <span>2) Scan</span>
                            </a>
                        </li>
                        {% endblock %}
                        {% block result_link %}
                        <li>
                            <a id="sidebar-review" href="/results" class="waves-effect">
                                <i class="ti-list"></i>
                                <span>3) Review</span>
                            </a>
                        </li>
                        {% endblock %}
                        <li class="text-muted menu-title">Account</li>
                        {% block password_change %}
                        <li>
                            <a href="{% url 'password_change' %}" class="waves-effect">
                                <i class="glyphicon glyphicon-lock"></i>
                                <span>Password</span>
							</a>
                        </li>
                        {% endblock %}
                        {% block logout %}
                        <li>
                            <a href="{% url 'logout' %}" class="waves-effect">
                                <i class="glyphicon glyphicon-chevron-left"></i>
                                <span>Logout </span></a>
                        </li>
                        {% endblock %}
                    </ul>
                    <div class="clearfix"></div>
                </div>
                {% endblock leftmenu %}
                <div class="clearfix"></div>
            </div>
        </div>
        <!-- Left Sidebar End -->

    </body>
</html>

<script>
    {#alert("sidebar-{{ page }}");#}
    const contentsLabel = document.getElementById("sidebar-{{ page }}");
    contentsLabel.className += " active";
</script>

Deloitte_Dynamics/templates/shared/topbar.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <body>

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- LOGO -->
            <div class="topbar-left">
                <div class="text-center">
                    <a target="_blank" href="https://www2.deloitte.com/uk/en.html" class="logo" style="height: 90px;">
                        <img src="{% static "assets/images/brand/ddot.png" %}" class="icon-c-logo" style="max-height:90px;"></img>
                        <span>
                            <img src="{% static "assets/images/brand/logo.png" %}"></img>
                        </span>
                    </a>
                </div>
            </div>
        </div>
        <!-- Top Bar End -->

    </body>
</html>